### ISSUE TITLE
Increase compatibility with newer ruby version

### ISSUE THREAD

**Issue by lacostej** [DragonBox/freshsales#16]
### Issue Description

```
/Users/lacostej/Code/WWTK/Backend/freshsales_mailchimp_syncer/.bundle/ruby/3.2.0/gems/freshsales-0.0.6/lib/freshsales/client.rb:45:in `freshsales_request': wrong number of arguments (given 3, expected 2) (ArgumentError)
	from /Users/lacostej/Code/WWTK/Backend/freshsales_mailchimp_syncer/.bundle/ruby/3.2.0/gems/freshsales-0.0.6/lib/freshsales/client.rb:10:in `httprequest'
	from /Users/lacostej/Code/WWTK/Backend/freshsales_mailchimp_syncer/.bundle/ruby/3.2.0/gems/freshsales-0.0.6/lib/freshsales/request_builder.rb:23:in `method_missing'
	from freshsales_dump_data.rb:32:in `dump_entities_from_view'
	from freshsales_dump_data.rb:67:in `<main>'
```

```
/Users/lacostej/Code/WWTK/Backend/freshsales_mailchimp_syncer/.bundle/ruby/3.2.0/gems/freshsales-0.0.6/lib/freshsales/cursor.rb:35:in `new': tried to create Proc object without a block (ArgumentError)
	from /Users/lacostej/Code/WWTK/Backend/freshsales_mailchimp_syncer/.bundle/ruby/3.2.0/gems/freshsales-0.0.6/lib/freshsales/cursor.rb:35:in `each'
	from freshsales_dump_data.rb:36:in `dump_entities_from_view'
	from freshsales_dump_data.rb:67:in `<main>'
```

**Comment by lacostej** [comment]
Fixed in 0.0.7
